In [52]:
import numpy as np
import colorsys
from nilearn import datasets
import nibabel as nib

In [5]:
atlas_data = datasets.fetch_atlas_msdl()
atlas_filename = atlas_data.maps
DMN = nib.load(atlas_filename)
DMNlabels = atlas_data.labels

c:\users\yin\appdata\local\programs\python\python36\lib\site-packages\numpy\lib\npyio.py:2266: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  output = genfromtxt(fname, **kwargs)


In [7]:
DMNaffine = DMN.get_affine()

c:\users\yin\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: get_affine method is deprecated.
Please use the ``img.affine`` property instead.

* deprecated from version: 2.1
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 4.0
  """Entry point for launching an IPython kernel.


In [9]:
DMNdata = DMN.get_fdata()

In [41]:
dmn = DMNdata[:,:,:,3:7]

In [42]:
dmn.shape

(40, 48, 35, 4)

In [43]:
tdmn = dmn>0

In [44]:
tdmn.sum()

1027

In [26]:
from nibabel.affines import apply_affine

In [24]:
for i in range(0,35,3):
    j = j+1
    print(j)

1
2
3
4
5
6
7
8
9
10
11
12


In [45]:
DMNpos = np.zeros(3*1027)
DMNpos = DMNpos.reshape(1027, 3)
o = 0
for s in range(4):
    D = dmn[:,:,:,s]
    for i in range(40):
        for j in range(48):
            for k in range(35):
                if D[i,j,k] > 0:
                    DMNpos[o,:] = i,j,k
                    o = o+1

In [46]:
DMNpos

array([[ 5., 11., 19.],
       [ 5., 11., 20.],
       [ 5., 11., 21.],
       ...,
       [35., 14., 21.],
       [35., 15., 18.],
       [36., 14., 18.]])

In [48]:
MNIDMNpos = np.zeros(DMNpos.shape)
for i in range(MNIDMNpos.shape[0]):
    get = DMNpos[i]
    at = apply_affine(DMNaffine,get)
    MNIDMNpos[i] = at

In [58]:
DMNMNI = np.load("C:\\Users\Yin\Desktop\ADHD200\MNIDMNpos.npy")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Yin\\Desktop\\ADHD200\\MNIspos.npy'

In [59]:
Pos

array([[ 72., -30.,  -6.],
       [ 66., -54.,  -6.],
       [ 66., -54.,   0.],
       ...,
       [-66.,  -6.,  12.],
       [-66.,  -6.,  18.],
       [-66.,  -6.,  24.]])

In [60]:
DMNMNI.shape

(1027, 3)

In [72]:
((Pos[2]-DMNMNI[2])**2).sum()

16634.0

In [74]:
a = np.array(range(19))

In [77]:
np.where(a==a.min())[0][0]

0

In [80]:
DMNinSpos = np.zeros(8468)
for k in range(1027):
    DMNpos = DMNMNI[k]
    temp = np.zeros(8468)
    for i in range(8468):
        temp[i] = ((Pos[i]-DMNpos)**2).sum()
    DMNinSpos[np.where(temp==temp.min())[0][0]] = 1

In [82]:
DMNinSpos.sum()

408.0

In [83]:
np.save("DMNinSpos",DMNinSpos)

In [51]:
np.save("MNIDMNpos",MNIDMNpos)

In [56]:
posdirc = "C:\\Users\Yin\Desktop\ADHD200\Pos\MNIspos.npy"
AALatlas = np.load("C:\\Users\Yin\Desktop\ADHD200\AALatlas.npy")
AALlabelsAb = np.load("C:\\Users\Yin\Desktop\ADHD200\AALlabelsAb.npy")
AALlabelsFu = np.load("C:\\Users\Yin\Desktop\ADHD200\AALlabelsFu.npy")
dic = "C:\\Users\Yin\Desktop\ADHD200\Pos\spos.npy"
Pos = np.load(posdirc)
spos = np.load(dic)

In [3]:
Pos.shape

(8468, 3)

In [4]:
spos

array([[ 9., 48., 33.],
       [12., 36., 33.],
       [12., 36., 36.],
       ...,
       [78., 60., 42.],
       [78., 60., 45.],
       [78., 60., 48.]])

In [5]:
AALatlas[1,3,2]

0

In [103]:
HSV = np.zeros(117*3)
HSV = HSV.reshape(117,3)

In [104]:
RGB = np.zeros(117*3)
RGB = RGB.reshape(117,3)

In [105]:
for i in range(1,117):
    if i == 0:
        H =0
        S =0
        V =100
    if  0<i< 34:
        H = 10*i
        S = 100
        V = 100
    if 33<i<66:
        H = 10*(i-33)
        S = 60
        V = 100
    if 66<i<99:
        H = 10*(i-66)
        S = 30
        V = 80
    if  99<i<117:
        H = 10*(i-99)
        S = 80
        V = 50
    HSV[i] = H,S,V

In [106]:
for i in range(0,117):
    h,s,v = HSV[i]
    h = h/360
    s = s/100
    v = v/100
    r,g,b = colorsys.hsv_to_rgb(h,s,v)
    RGB[i] = r,g,b

In [107]:
RGB = RGB*255

In [108]:
RGB

array([[  0. ,   0. ,   0. ],
       [255. ,  42.5,   0. ],
       [255. ,  85. ,   0. ],
       [255. , 127.5,   0. ],
       [255. , 170. ,   0. ],
       [255. , 212.5,   0. ],
       [255. , 255. ,   0. ],
       [212.5, 255. ,   0. ],
       [170. , 255. ,   0. ],
       [127.5, 255. ,   0. ],
       [ 85. , 255. ,   0. ],
       [ 42.5, 255. ,   0. ],
       [  0. , 255. ,   0. ],
       [  0. , 255. ,  42.5],
       [  0. , 255. ,  85. ],
       [  0. , 255. , 127.5],
       [  0. , 255. , 170. ],
       [  0. , 255. , 212.5],
       [  0. , 255. , 255. ],
       [  0. , 212.5, 255. ],
       [  0. , 170. , 255. ],
       [  0. , 127.5, 255. ],
       [  0. ,  85. , 255. ],
       [  0. ,  42.5, 255. ],
       [  0. ,   0. , 255. ],
       [ 42.5,   0. , 255. ],
       [ 85. ,   0. , 255. ],
       [127.5,   0. , 255. ],
       [170. ,   0. , 255. ],
       [212.5,   0. , 255. ],
       [255. ,   0. , 255. ],
       [255. ,   0. , 212.5],
       [255. ,   0. , 170. ],
       [25

In [109]:
colors = np.zeros(8468*3)
colors = colors.reshape(8468,3)

In [110]:
RGB.shape

(117, 3)

In [ ]:
colors = np.zeros(8468*3)
colors = colors.reshape(8468,3)

In [13]:
markpos = np.zeros(8468)

In [111]:
for i in range(8468):
    x,y,z = spos[i].astype(int)
    mark = AALatlas[x,y,z]
    r,g,b = RGB[mark]
    colors[i] = r,g,b

In [14]:
for i in range(8468):
    x,y,z = spos[i].astype(int)
    mark = AALatlas[x,y,z]
    markpos[i] = mark

In [16]:
markpos.shape

(8468,)

In [114]:
np.save("colorMap",colors)

In [17]:
np.save("AAlatlasMap",markpos)

In [18]:
markpos.shape

(8468,)

In [20]:
markpos== 2

array([False, False, False, ..., False, False, False])

In [22]:
l  =np.where(markpos==2)

In [34]:
l2 = np.where(markpos==3)

In [43]:
l2[0]

array([5297, 5315, 5330, 5333, 5346, 5347, 5361, 5362, 5363, 5377, 5378,
       5379, 5392, 5393, 5394, 5395, 5406, 5407, 5408, 5409, 5419, 5420,
       5421, 5422, 5423, 5432, 5433, 5434, 5435, 5436, 5445, 5446, 5447,
       5448, 5456, 5458, 5463, 5465, 5466, 5468, 5784, 5801, 5802, 5804,
       5821, 5822, 5823, 5824, 5840, 5841, 5842, 5843, 5855, 5856, 5857,
       5858, 5859, 5871, 5872, 5873, 5874, 5886, 5887, 5888, 5889, 5899,
       5900, 5901, 5902, 5903, 5912, 5913, 5914, 5915, 5922, 5925, 5926,
       5930, 5931, 5932, 5933, 5934, 5935, 5936, 5940, 5941, 5942, 5943,
       5944, 5945, 5948, 5949, 5950, 5951, 5952, 6234, 6254, 6255, 6256,
       6257, 6277, 6278, 6298, 6318, 6335, 6337, 6375, 6377, 6388, 6389,
       6393, 6400, 6403, 6404, 6407, 6412, 6413, 6414, 6415, 6416, 6417,
       6420, 6421, 6422, 6714, 6734, 6843, 6847, 6856, 6864, 6868, 7287],
      dtype=int64)

In [40]:
l3 = np.append(l[0],l2[0])

In [44]:
l3

array([  96,  231,  244,  253,  254,  255,  256,  428,  429,  445,  446,
        458,  459,  460,  461,  462,  463,  473,  475,  476,  477,  478,
        491,  492,  707,  708,  710,  725,  726,  727,  728,  742,  743,
        744,  746,  759,  760,  761,  762,  763,  777,  778,  779,  780,
       1050, 1051, 1065, 1066, 1067, 1068, 1069, 1083, 1084, 1085, 1086,
       1087, 1088, 1103, 1104, 1105, 1107, 1122, 1123, 1124, 1139, 1141,
       1142, 1462, 1463, 1464, 1478, 1479, 1480, 1481, 1482, 1498, 1499,
       1500, 1501, 1518, 1519, 1536, 1537, 1538, 1897, 1898, 1899, 1900,
       1916, 1917, 1918, 1935, 1938, 1955, 1956, 1975, 2346, 2347, 2363,
       2364, 2365, 2381, 2382, 2383, 2831, 2832, 2850, 2851, 2852, 2869,
       2870, 2871, 3319, 3360, 5297, 5315, 5330, 5333, 5346, 5347, 5361,
       5362, 5363, 5377, 5378, 5379, 5392, 5393, 5394, 5395, 5406, 5407,
       5408, 5409, 5419, 5420, 5421, 5422, 5423, 5432, 5433, 5434, 5435,
       5436, 5445, 5446, 5447, 5448, 5456, 5458, 54

In [30]:
for i in l[0]:
    print(i)

96
231
244
253
254
255
256
428
429
445
446
458
459
460
461
462
463
473
475
476
477
478
491
492
707
708
710
725
726
727
728
742
743
744
746
759
760
761
762
763
777
778
779
780
1050
1051
1065
1066
1067
1068
1069
1083
1084
1085
1086
1087
1088
1103
1104
1105
1107
1122
1123
1124
1139
1141
1142
1462
1463
1464
1478
1479
1480
1481
1482
1498
1499
1500
1501
1518
1519
1536
1537
1538
1897
1898
1899
1900
1916
1917
1918
1935
1938
1955
1956
1975
2346
2347
2363
2364
2365
2381
2382
2383
2831
2832
2850
2851
2852
2869
2870
2871
3319
3360


In [38]:
l[0][1]

231

In [27]:
l

(array([  96,  231,  244,  253,  254,  255,  256,  428,  429,  445,  446,
         458,  459,  460,  461,  462,  463,  473,  475,  476,  477,  478,
         491,  492,  707,  708,  710,  725,  726,  727,  728,  742,  743,
         744,  746,  759,  760,  761,  762,  763,  777,  778,  779,  780,
        1050, 1051, 1065, 1066, 1067, 1068, 1069, 1083, 1084, 1085, 1086,
        1087, 1088, 1103, 1104, 1105, 1107, 1122, 1123, 1124, 1139, 1141,
        1142, 1462, 1463, 1464, 1478, 1479, 1480, 1481, 1482, 1498, 1499,
        1500, 1501, 1518, 1519, 1536, 1537, 1538, 1897, 1898, 1899, 1900,
        1916, 1917, 1918, 1935, 1938, 1955, 1956, 1975, 2346, 2347, 2363,
        2364, 2365, 2381, 2382, 2383, 2831, 2832, 2850, 2851, 2852, 2869,
        2870, 2871, 3319, 3360], dtype=int64),)

In [ ]:
partlist = np.append(chosepart(m1),chosepart(m2))